export const LOAD_TFUS_SUCCESS = "LOAD_TFUS_SUCCESS";
export const LOAD_TFUS_FAIL = "LOAD_TFUS_FAIL";
export const CLEAR_HOMEPAGE = "CLEAR_HOMEPAGE";
export const LOADING_TWEETS = "LOADING_TWEETS";
export const LOADING_TWEETS_SUCCESS = "LOADING_TWEETS_SUCCESS";
export const LOADING_TWEETS_FAIL = "LOADING_TWEETS_FAIL";
