export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL";
export const LOADED_USER_INFO = "LOADED_USER_INFO";
export const LOAD_FOLLOWED_USERS_SUCCESS = "LOAD_FOLLOWED_USERS_SUCCESS";
export const LOAD_FOLLOWED_USERS_FAIL = "LOAD_FOLLOWED_USERS_FAIL";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";
